#!/usr/bin/env python3
"""Build the builder's reported-network-accuracy table from the curated literature notes."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

TRAINING = {"nat", "qat", "unstated"}
CONFIDENCE = {"high", "medium", "low"}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="scripts/sources/network-accuracy.json")
    parser.add_argument("csv", type=Path, help="Benchmarking_Data.csv, to check paper indices")
    parser.add_argument("output", type=Path, help="Generated JavaScript output")
    args = parser.parse_args()

    data = json.loads(args.source.read_text(encoding="utf-8"))
    with args.csv.open(encoding="utf-8-sig") as handle:
        indices = {(row.get("Index") or "").strip() for row in csv.DictReader(handle)}

    for index, paper in data["papers"].items():
        where = f"paper #{index}"
        assert index in indices, f"{where} is not in the CSV"
        assert paper["training"] in TRAINING, f"{where}: training {paper['training']!r}"
        assert paper["confidence"] in CONFIDENCE, f"{where}: confidence {paper['confidence']!r}"
        assert paper["entries"] or paper.get("summary"), f"{where}: needs entries or a summary"
        assert paper["sources"] and all(source["url"].startswith("http") for source in paper["sources"]), f"{where}: sources"
        for entry in paper["entries"]:
            assert isinstance(entry["chip"], (int, float)), f"{where}: chip accuracy"
            assert entry["baseline"] is None or isinstance(entry["baseline"], (int, float)), f"{where}: baseline"
            assert entry["task"] and entry["evidence"], f"{where}: task and evidence"

    payload = {"collected": data["meta"]["collected"], "method": data["meta"]["method"], "papers": data["papers"]}
    notice = """// Generated by scripts/build-network-accuracy.py from scripts/sources/network-accuracy.json.
// Network-level accuracy reported by the benchmark's analog IMC papers, with training method and sources.
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(notice + "window.IMC_NETWORK_ACCURACY = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"{len(data['papers'])} papers written to {args.output}")


if __name__ == "__main__":
    main()
