#!/usr/bin/env python3
"""Build the browser-side ASiM accuracy tables from a transcription of the published figures."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ENCODINGS = ("bitSerial", "2", "4")


def points(table: dict) -> list:
    return [[float(key), value] for key, value in sorted(table.items(), key=lambda item: float(item[0]))]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="Transcribed ASiM figure tables (scripts/sources/asim-figure-tables.json)")
    parser.add_argument("output", type=Path, help="Generated JavaScript output")
    args = parser.parse_args()

    data = json.loads(args.source.read_text(encoding="utf-8"))
    meta = data["meta"]
    workloads = {}
    for key, workload in data["workloads"].items():
        adc = {encoding: points(workload["fig7_adcByEncoding"][encoding]) for encoding in ENCODINGS}
        # Fig. 6 extends the bit-serial sweep below Fig. 7's 8-bit minimum.
        below_fig7 = [point for point in points(workload["fig6_bitSerialAdc"]) if point[0] < 8]
        adc["bitSerial"] = below_fig7 + adc["bitSerial"]
        non_nat = workload.get("fig18_nonNatRandomNoise")
        workloads[key] = {
            "baseline": workload["digitalBaseline"]["top1"],
            "nonNatBaseline": workload.get("nonNatDigitalBaseline", {}).get("top1"),
            "adc": adc,
            "randomNoise": {encoding: points(workload["fig9a_randomNoise"][encoding]) for encoding in ENCODINGS},
            "nonlinearity": {encoding: points(workload["fig9b_nonlinearity"][encoding]) for encoding in ENCODINGS},
            "nonNatRandomNoise": {encoding: points(non_nat[encoding]) for encoding in ENCODINGS} if non_nat else None,
        }

    validation = meta["siliconValidation_CRCIM"]
    payload = {
        "paper": meta["source"]["paper"],
        "arxiv": meta["source"]["absUrl"],
        "repository": "https://github.com/Keio-CSG/ASiM",
        "rows": 256,
        "weightBits": 8,
        "inputBits": 8,
        "noiseAdcBits": 8,
        "figures": "ADC precision: Figs. 6-7 (no analog noise). Random noise: Fig. 9a. Nonlinearity: Fig. 9b. "
        "Random noise without NAT: Fig. 18. Noise figures use an 8-bit ADC.",
        "siliconValidation": {
            "asimPredictedTop1": validation["asimPredictedTop1"],
            "measuredTop1": validation["measuredTop1"],
        },
        "workloads": workloads,
    }

    notice = """// Generated by scripts/build-asim-data.py from a transcription of the ASiM figure tables
// (arXiv:2411.11022v4, Figs. 6, 7, 9 and 18). Values are top-1 accuracy in percent.
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        notice + "window.IMC_ASIM_DATA = " + json.dumps(payload, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
